---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  labels:
    name: api-server-deployment
    app: api-server
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-server-pod
      app: api-server
      tier: app
  template:
    metadata:
      name: api-server-pod
      labels:
        name: api-server-pod
        app: api-server
        tier: app
    spec:
      containers:
      - name: api-server-container
        image: registry.cloud.okteto.net/cdsdemo-weikangchia/apiserver
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "250Mi"
            cpu: "500m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-svc
  labels:
    name: api-server-svc
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  selector:
    name: api-server-pod
    app: api-server
    tier: app
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 80