---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
  labels:
    name: krakend-deployment
    app: krakend
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: krakend-pod
      app: krakend
      tier: app
  template:
    metadata:
      name: krakend-pod
      labels:
        name: krakend-pod
        app: krakend
        tier: app
    spec:
      containers:
      - name: krakend-container
        image: devopsfaith/krakend:1.4.1-alpine
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/config/krakend/krakend.json", "-p", "8080" ]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: KRAKEND_PORT
          value: "8080"
        resources:
          requests:
            memory: "250Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "50m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/krakend
      volumes:
      - name: config-volume
        configMap:
          name: krakend-cm
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-cm
  labels:
    name: krakend-cm
data:
  krakend.json: |
    {
      "version": 2,
      "endpoints": [
        {
          "endpoint": "/apiserver/v1/users",
          "method": "GET",
          "output_encoding": "json",
          "backend": [
            {
              "url_pattern": "/users",
              "encoding": "json",
              "method": "GET",
              "host": [
                "http://api-server-svc.cdsdemo-weikangchia.svc.cluster.local"
              ],
              "deny": [
                "hiddenFlag"
              ]
            }
          ]
        }
      ],
      "extra_config": {}
    }
---
apiVersion: v1
kind: Service
metadata:
  name: krakend-svc
  labels:
    name: krakend-svc
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  selector:
    name: krakend-pod
    app: krakend
    tier: app
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 80